# fly.toml app configuration file generated for nema-frontend on 2025-01-29T00:00:00-00:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nema-frontend'
primary_region = 'yyz'

[build]

[http_service]
  auto_start_machines = true
  auto_stop_machines = 'stop'
  force_https = true
  internal_port = 8080
  min_machines_running = 0
  processes = [
    'app',
  ]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '512mb'
  size = 'shared-cpu-1x'

# Static file serving configuration
[http_service.http_options]
  # Enable gzip compression
  compress = true