# fly.toml app configuration file generated for nema-frontend on 2025-02-17T12:27:13-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nema-frontend'
primary_region = 'yyz'

[build]

[http_service]
  auto_start_machines = true
  auto_stop_machines = 'stop'
  force_https = true
  internal_port = 3000
  min_machines_running = 0
  processes = [
    'app',
  ]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '512mb'
  size = 'shared-cpu-1x'
